// src/components/svelte/onboarding/NavigationControls.svelte
<script lang="ts">
  // Converted from React NavigationControls.tsx with runes
  import { getPaymentStatus } from "@/services/payment";
  
  export let currentStep = 1;
  export let totalSteps = 3;
  export let onPrevious: () => void;
  export let onNext: () => void;
  export let onFinish: () => Promise<void>;
  // Pass in value from outside, but fall back to our own check if not provided
  export let isPaidOrTrialing: boolean | undefined = undefined;
  
  let internalPaidStatus = $state(false);
  let intervalId: ReturnType<typeof setInterval> | null = $state(null);
  
  // Derived value using effect values
  const effectivePaidStatus = $derived(
    isPaidOrTrialing !== undefined ? isPaidOrTrialing : internalPaidStatus
  );
  
  const isLastStep = $derived(currentStep === totalSteps);
  
  // Check payment status function
  async function checkPaymentStatus() {
    try {
      const status = await getPaymentStatus();
      internalPaidStatus = status.paid || status.trialIsValid;
    } catch (error) {
      console.error("Error checking payment status:", error);
      internalPaidStatus = false;
    }
  }
  
  // Run when currentStep changes
  $effect(() => {
    if (currentStep === totalSteps && isPaidOrTrialing === undefined) {
      checkPaymentStatus();
    }
  });
  
  // Setup polling when on last step
  $effect(() => {
    // Clean up previous interval if it exists
    if (intervalId) {
      clearInterval(intervalId);
      intervalId = null;
    }
    
    // Only run our own check if no external status is provided
    if (currentStep === totalSteps && isPaidOrTrialing === undefined) {
      // Initial check
      checkPaymentStatus();
      
      // Set up polling to check every second
      intervalId = setInterval(checkPaymentStatus, 1000);
    }
    
    // Clean up when component is destroyed
    return () => {
      if (intervalId) {
        clearInterval(intervalId);
        intervalId = null;
      }
    };
  });
</script>

<div class="controls">
  <div class="buttons-container">
    {#if currentStep > 1}
      <button class="btn btn-secondary" on:click={onPrevious}>
        Previous
      </button>
    {/if}
    
    {#if currentStep < totalSteps}
      <button class="btn btn-primary" on:click={onNext}>
        Next
      </button>
    {/if}
    
    {#if isLastStep}
      <div style="position: relative">
        <button 
          class="btn btn-primary" 
          on:click={onFinish} 
          disabled={!effectivePaidStatus}
          title={!effectivePaidStatus ? "Please start a trial or make a purchase to continue" : ""}
        >
          Get Started
        </button>
        
        {#if !effectivePaidStatus}
          <div style="position: absolute; top: -25px; left: 50%; transform: translateX(-50%); background-color: #e25822; color: white; padding: 3px 8px; border-radius: 4px; font-size: 12px; white-space: nowrap">
            Start trial or buy first
          </div>
        {/if}
      </div>
    {/if}
  </div>
</div>

// src/components/react/onboarding/NavigationControls.tsx
import React from "react";
import { getPaymentStatus } from "@/services/payment";

interface NavigationControlsProps {
  currentStep: number;
  totalSteps: number;
  onPrevious: () => void;
  onNext: () => void;
  onFinish: () => Promise<void>;
  isPaidOrTrialing?: boolean;
}

const NavigationControls: React.FC<NavigationControlsProps> = ({
  currentStep,
  totalSteps,
  onPrevious,
  onNext,
  onFinish,
  isPaidOrTrialing: externalPaidStatus,
}) => {
  const [internalPaidStatus, setInternalPaidStatus] = React.useState(false);

  // If external status is provided, use it, otherwise use internal status
  const isPaidOrTrialing = externalPaidStatus !== undefined ? externalPaidStatus : internalPaidStatus;

  // Check payment status when we're on the last step
  React.useEffect(() => {
    // Only run our own check if no external status is provided
    if (currentStep === totalSteps && externalPaidStatus === undefined) {
      const checkPaymentStatus = async () => {
        try {
          const status = await getPaymentStatus();
          setInternalPaidStatus(status.paid || status.trialIsValid);
        } catch (error) {
          console.error("Error checking payment status:", error);
          setInternalPaidStatus(false);
        }
      };
      
      // Run initial check
      checkPaymentStatus();
      
      // Set up polling to check every second
      const intervalId = setInterval(checkPaymentStatus, 1000);
      
      // Clear interval when component unmounts or step changes
      return () => clearInterval(intervalId);
    }
  }, [currentStep, totalSteps, externalPaidStatus]);

  return (
    <div className="controls">
      <div className="buttons-container">
        {currentStep > 1 && (
          <button className="btn btn-secondary" onClick={onPrevious}>
            Previous
          </button>
        )}
        {currentStep < totalSteps && (
          <button className="btn btn-primary" onClick={onNext}>
            Next
          </button>
        )}
        {currentStep === totalSteps && (
          <div style={{ position: "relative" }}>
            <button 
              className="btn btn-primary" 
              onClick={onFinish} 
              disabled={!isPaidOrTrialing}
              title={!isPaidOrTrialing ? "Please start a trial or make a purchase to continue" : ""}
            >
              Get Started
            </button>
            {!isPaidOrTrialing && (
              <div style={{ 
                position: "absolute", 
                top: "-25px", 
                left: "50%", 
                transform: "translateX(-50%)",
                backgroundColor: "#e25822",
                color: "white",
                padding: "3px 8px",
                borderRadius: "4px",
                fontSize: "12px",
                whiteSpace: "nowrap"
              }}>
                Start trial or buy first
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default NavigationControls;
