// src/components/svelte/popup/MonitorsCount.svelte
<script lang="ts">
  import browser from "webextension-polyfill";

  const { alarmCount } = $props<number>();

  function handleManageClick() {
    browser.tabs.create({ url: browser.runtime.getURL("manage.html") });
  }
</script>

<div class="monitors-count">
  <div class="flex-row">
    <span>
      Active monitors: <strong>{alarmCount}</strong> / 500
    </span>
    {#if alarmCount >= 400 && alarmCount < 475}
      <span id="alarm-count-warning">⚠️ Approaching limit</span>
    {/if}
    {#if alarmCount >= 475}
      <span id="alarm-count-error">⚠️ At limit</span>
    {/if}
  </div>
</div>

<style>
  .monitors-count {
    margin-bottom: 16px;
    padding: 12px;
    border-radius: 6px;
    background-color: #f6f8fa;
  }

  .flex-row {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  strong {
    font-weight: 600;
  }

  #alarm-count-warning {
    color: #d29922;
    font-size: 14px;
  }

  #alarm-count-error {
    color: #cb2431;
    font-size: 14px;
  }
</style>

// src/components/react/popup/MonitorsCount.tsx
import React from "react";
import browser from "webextension-polyfill";

interface MonitorsCountProps {
  alarmCount: number;
}

const MonitorsCount: React.FC<MonitorsCountProps> = ({ alarmCount }) => {
  const handleManageClick = () => {
    browser.tabs.create({ url: browser.runtime.getURL("manage.html") });
  };

  return (
    <div className="monitors-count">
      <div className="flex-row">
        <span>
          Active monitors: <strong>{alarmCount}</strong> / 500
        </span>
        {alarmCount >= 400 && alarmCount < 475 && (
          <span id="alarm-count-warning">⚠️ Approaching limit</span>
        )}
        {alarmCount >= 475 && <span id="alarm-count-error">⚠️ At limit</span>}
      </div>
      {alarmCount > 0 && (
        <div className="manage-section">
          <div className="flex-row">
            <button className="secondary" onClick={handleManageClick}>
              Manage Active Monitors
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default MonitorsCount;
