// src/components/react/manage/StatusBar.tsx
import React from "react";

interface StatusBarProps {
  monitorCount: number;
  refreshing: boolean;
  onRefresh: () => Promise<void>;
  onClearAll: () => Promise<boolean | undefined>;
  hasMonitors: boolean;
}

const StatusBar: React.FC<StatusBarProps> = ({
  monitorCount,
  refreshing,
  onRefresh,
  onClearAll,
  hasMonitors,
}) => {
  // Determine status bar class based on monitor count
  const getStatusBarClass = () => {
    if (monitorCount >= 475) {
      return "status-bar error";
    } else if (monitorCount >= 400) {
      return "status-bar warning";
    } else {
      return "status-bar";
    }
  };

  return (
    <div className={getStatusBarClass()}>
      <div>
        Active monitors: <strong>{monitorCount}</strong> / 500
      </div>
      <div>
        <button className="secondary" onClick={onRefresh} disabled={refreshing}>
          {refreshing && <span className="spinner"></span>}
          Refresh
        </button>
        <button
          className="danger bulk-action"
          disabled={!hasMonitors}
          onClick={onClearAll}
        >
          Clear All Monitors
        </button>
      </div>
    </div>
  );
};

export default StatusBar;

// src/components/svelte/manage/StatusBar.svelte
<script lang="ts">
  const { onRefresh, onClearAll } = $props();

  let monitorCount = $state(0);
  let refreshing = $state(false);
  let hasMonitors = $derived(monitorCount > 0);

  // Determine status bar class based on monitor count - proper runes usage
  const statusBarClass = $derived(
    monitorCount >= 475
      ? "status-bar error"
      : monitorCount >= 400
        ? "status-bar warning"
        : "status-bar"
  );
</script>

<div class={statusBarClass}>
  <div>
    Active monitors: <strong>{monitorCount}</strong> / 500
  </div>
  <div>
    <button class="secondary" onclick={onRefresh} disabled={refreshing}>
      {#if refreshing}<span class="spinner"></span>{/if}
      Refresh
    </button>
    <button
      class="danger bulk-action"
      disabled={!hasMonitors}
      onclick={onClearAll}
    >
      Clear All Monitors
    </button>
  </div>
</div>
